### ISSUE TITLE
Update to source-map 0.6.1 causes an error when running Webpack

### ISSUE THREAD

**Issue by wvankuipers** [webpack/webpack-sources#28] opened 2017-11-04 12:29 UTC
This update seems to create another issue (this is also reported [here](https://github.com/webpack/webpack-sources/pull/27#issuecomment-341891811)):

```
frontend/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276
        throw new Error(
        ^

Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
    at SourceMapGenerator_validateMapping [as _validateMapping] (frontend/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276:15)
    at SourceMapGenerator_addMapping [as addMapping] (frontend/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:110:12)
    at frontend/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:72:17
    at Array.forEach (<anonymous>)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (frontend/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consumer.js:157:14)
    at Function.SourceMapGenerator_fromSourceMap [as fromSourceMap] (frontend/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:48:24)
    at SourceMapSource.node (frontend/node_modules/webpack-sources/lib/SourceMapSource.js:32:35)
    at SourceMapSource.proto.sourceAndMap (frontend/node_modules/webpack-sources/lib/SourceAndMapMixin.js:30:18)
    at getTaskForFile (frontend/node_modules/webpack/lib/SourceMapDevToolPlugin.js:33:30)
    at chunk.files.forEach.file (frontend/node_modules/webpack/lib/SourceMapDevToolPlugin.js:91:21)
```

Reverting to v1.0.1 resolves this issue.

**Comment by d3viant0ne** [comment] 2017-11-05 04:00
@wvankuipers - I've tried `v1.0.2` in quite a few spots without being able to repo this.

Issues with `source-map@0.6.x` are pretty wide spread from what I have read thus far, meteor among others.

There is no changelog for either of the `0.6.x` releases & quite a few commits to sift through. I can't repo with anything I have access to, either getting a look at what you are having trouble with or anything minimal where this can be repro'd would be extremely helpful.

**Comment by wvankuipers** [comment] 2017-11-05 07:34
I created a simple example here https://github.com/wvankuipers/webpack-test

It seems to be specific to `Backbone.Marionette` in combination with the `babel-minify-webpack-plugin` package.

**Comment by wvankuipers** [comment] 2017-11-06 06:55
I did some more research and it seems to be coming down to [this line](https://github.com/marionettejs/backbone.marionette/blob/master/lib/backbone.marionette.js#L16) in the Backbone.Marionette library:

    typeof define === 'function' && define.amd ? define(['backbone', 'underscore', 'backbone.radio'], factory) :

And then specificly

    define(['backbone', 'underscore', 'backbone.radio'], factory)

Even removing the rest of that file's content and leaving only this part there will cause Webpack to fail with the error above... Removing this line and Webpack wil succeed.

**Comment by wvankuipers** [comment] 2017-11-06 07:22
A (temporary) workaround for this issue is to add

    sourceMap: null

To the configuration of the `babel-minify-webpack-plugin` package.

**Comment by dancollingridge** [comment] 2017-11-06 22:07
Same issue here. I had to force install version 1.0.1 (rather than letting webpack pull in its own version) to get my project to build:

`"webpack": "^2.2.1",
+    "webpack-sources": "1.0.1",
     "webpack-bundle-analyzer": "^2.2.1",
     "webpack-dev-middleware": "^1.10.0",
     "webpack-hot-middleware": "^2.16.1",
`

**Comment by michael-ciniawsky** [comment] 2017-11-06 22:35
@dancollingridge Could you provide Error logs and a bit of relevant context about your project ?

**Comment by fkarczeski** [comment] 2017-11-06 22:56
I also had the same issue.

Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.

    at SourceMapGenerator_validateMapping [as _validateMapping] (webpack-repo\node_modules\webpack-sources\node_modules\source-map\lib\source-map-generator.js:276:15)
    at SourceMapGenerator_addMapping [as addMapping] (webpack-repo\node_modules\webpack-sources\node_modules\source-map\lib\source-map-generator.js:110:12)
    at webpack-repo\node_modules\webpack-sources\node_modules\source-map\lib\source-map-generator.js:72:17
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (webpack-repo\node_modules\webpack-sources\node_modules\source-map\lib\source-map-consumer.js:157:14)
    at Function.SourceMapGenerator_fromSourceMap [as fromSourceMap] (webpack-repo\node_modules\webpack-sources\node_modules\source-map\lib\source-map-generator.js:48:24)
    at SourceMapSource.node (webpack-repo\node_modules\webpack-sources\lib\SourceMapSource.js:32:35)
    at SourceMapSource.proto.sourceAndMap (webpack-repo\node_modules\webpack-sources\lib\SourceAndMapMixin.js:30:18)
    at getTaskForFile (webpack-repo\node_modules\webpack\lib\SourceMapDevToolPlugin.js:33:30)
    at chunk.files.forEach.file (webpack-repo\node_modules\webpack\lib\SourceMapDevToolPlugin.js:91:21)
    at Array.forEach (native)
    at webpack-repo\node_modules\webpack\lib\SourceMapDevToolPlugin.js:89:18
    at Array.forEach (native)
    at Compilation.<anonymous> (webpack-repo\node_modules\webpack\lib\SourceMapDevToolPlugin.js:88:12)
    at Compilation.applyPlugins1 (webpack-repo\node_modules\tapable\lib\Tapable.js:75:14)
    at self.applyPluginsAsync.err (webpack-repo\node_modules\webpack\lib\Compilation.js:644:11)
    at next (webpack-repo\node_modules\tapable\lib\Tapable.js:202:11)
    at Compilation.<anonymous> (webpack-repo\node_modules\babili-webpack-plugin\lib\index.js:106:11)
    at next (webpack-repo\node_modules\tapable\lib\Tapable.js:204:14)
    at webpack-repo\node_modules\last-call-webpack-plugin\index.js:156:7
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by michael-ciniawsky** [comment] 2017-11-06 23:12
@fkarczeski Could you try without the `babili-webpack-plugin` please ?

@dancollingridge Are you also using `babili-webpack-plugin` for minification?

**Comment by dancollingridge** [comment] 2017-11-06 23:13
Exact same trace as posted above.

My app is a Vue.js app.

package.json target is:

```
"build": "node build/build.js",
```

`npm run build` produces:

```
$: npm run build
npm info it worked if it ends with ok
npm info using npm@4.2.0
npm info using node@v7.9.0
npm info lifecycle lift@0.1.0~prebuild: lift@0.1.0
npm info lifecycle lift@0.1.0~build: lift@0.1.0

> lift@0.1.0 build /var/www/lift
> node build/build.js

⠹ building for production.../var/www/lift/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276
        throw new Error(
        ^

Error: original.line and original.column are not numbers -- you probably mea.............
```

**Comment by dancollingridge** [comment] 2017-11-06 23:14
Yes, I am using babili-webpack-plugin.

**Comment by dancollingridge** [comment] 2017-11-06 23:15
In build/webpack.prod.conf.js:

```
var BabiliPlugin = require("babili-webpack-plugin")
//.......a bunch of other code.......
new BabiliPlugin({}, {}),
//.......a bunch of other code.......
```

**Comment by michael-ciniawsky** [comment] 2017-11-06 23:22
@dancollingridge Does the build succeed without `babili-webpack-plugin` ? 

```js
new BabiliPlugin({}*, {}*),
```

is this* 'pseudo'  or did you try without any options ?

**Comment by michael-ciniawsky** [comment] 2017-11-06 23:26
@all Which version of `babili-webpack-plugin` ?

>  ⚠️ It was recently renamed to `babel-minify-webpack-plugin` which includes a newer version of `babel-minify` (former `babili`)

**Comment by michael-ciniawsky** [comment] 2017-11-06 23:26
cc @boopathi

**Comment by fkarczeski** [comment] 2017-11-06 23:34
@michael-ciniawsky , not calling BabiliPlugin works (as expected).

This is my current set up that fails:
new BabiliPlugin({}, require("babel-preset-minify"))

Calling with no options also fails for me with the same error:
new BabiliPlugin({}, {})

babili-webpack-plugin "version": "0.1.2"

**Comment by michael-ciniawsky** [comment] 2017-11-07 00:12
Yep, the plugin uses `webpack-sources` directly to update the assets

**Comment by dancollingridge** [comment] 2017-11-07 05:03
If I disable `babili-webpack-plugin` in webpack.config the build works.

If I replace `babili-webpack-plugin` with `babel-minify-webpack-plugin` I get the same error as before.

**Comment by wvankuipers** [comment] 2017-11-07 06:36
I also tried both `babili-weback plugin` and `babel-minify-webpack-plugin` and found them both giving the same error. As [proposed](https://github.com/webpack/webpack-sources/pull/27#issuecomment-342290036) by @mattdsteele I [created a issue](https://github.com/mozilla/source-map/issues/304) in the `source-map` project as this seems not to be purely related to the `webpack-sources` package.

**Comment by breadadams** [comment] 2017-11-17 14:21
I'm using `babel-minify-webpack-plugin@0.2.0`, forcing `webpack-sources` to `1.0.1` in package.json as @dancollingridge suggested appears to fix it for now (as many more have said here https://github.com/webpack/webpack/issues/5931)

**Comment by jussikinnula** [comment] 2017-12-12 10:30
I'm also interested in this.

**Comment by nealoke** [comment] 2017-12-16 16:12
Just wanted to chip in and say that in my case it doesn't matter if i use the `BabiliPlugin()` or not, as long as I don't have the `"webpack-sources": "1.0.1"` installed it always fails. 

Also wanted to provide you with my files used:
- [`package.json`](https://gist.github.com/nealoke/b9adc553b63d09e5be3ef8b012d51fde#file-package-json)
- [`webpack.config.js`](https://gist.github.com/nealoke/b9adc553b63d09e5be3ef8b012d51fde#file-webpack-config-js)
- [`webpack.config.production.js`
](https://gist.github.com/nealoke/b9adc553b63d09e5be3ef8b012d51fde#file-webpack-config-production-js)
**Cases**
- `npm run server` -> no error
- `npm run server:test` -> error (if `webpack-sources@1.0.1` is not explicitly installed)
- `npm run build:prod` -> no error

**Comment by catamphetamine** [comment] 2017-12-20 23:47
Replacing `require('babili-weback-plugin')` with `require('uglifyjs-webpack-plugin')` works

**Comment by glixlur** [comment] 2017-12-21 11:39
@catamphetamine It works because then you’d be using an entirely different thing.

**Comment by anthonator** [comment] 2018-02-01 14:27
Has anyone tried `source-map` 0.7.0?

**Comment by SEAPUNK** [comment] 2018-02-06 23:13
So is the solution here to just not use the babili plugin, or is there a version we can bump to get rid of this error?

**Comment by scottohara** [comment] 2018-02-06 23:36
If you can wait a couple of weeks **and** assuming you will be able to upgrade immediately;  `webpack@4.x` will come with support for UglifyJS2 (expected on or around Feb 24).

I have a number of projects using `babel-minify-webpack-plugin` that have been affected by this issue since it first started on 4 November (when `webpack-sources@1.0.2` was released), and I've been patiently waiting for a fix now for three months. Another couple of weeks (for me) isn't going to hurt.  The only reason I was using `babel-minify` was for it's support for >ES5, and since UglifyJS2 will now have this, there's little reason for me to stick with the former.

It seems like nobody really wants to take ownership of the problem.

Despite numerous examples showing how to reproduce the problem, some of the early comments in the issue over in `mozilla/source-map` (https://github.com/mozilla/source-map/issues/304) seem to suggest that they think their library _is_ working as intended, and that any 'fix' belongs elsewhere.

In `webpack/webpack-sources` (here), the problem clearly started when moving to `source-map@0.6.0`; and comments in this thread suggest that they believe the problem squarely lies with `source-map`.

**Comment by SEAPUNK** [comment] 2018-02-06 23:48
@scottohara To be honest, I'm not really interested in UglifyJS2; I chose babel-minify, and I want to stick with it. Switching back to UJS2 won't solve this issue.

In the meantime, the workaround I implemented was forcing webpack to switch to webpack-sources@1.0.1.

**Comment by wvankuipers** [comment] 2018-05-06 17:16
Seems to be an issue with https://github.com/webpack-contrib/babel-minify-webpack-plugin/issues/68 but not sure if it is originated in this project or babel-minify

**Comment by evilebottnawi** [comment] 2018-08-30 16:53
We use latest `source-map` version with compatibility `node@6` (https://github.com/webpack/webpack-sources/blob/master/package.json#L19), will be updated after we drop support `node@6`, plugins can use own version, feel free create issue where we use old version

**Closed by evilebottnawi** 2018-08-30 16:53 UTC
